---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Copy the Script
      copy:
        src: /home/sverma/ansible/nwr/overall_report/tecmint_monitor.sh
        dest: /tmp
        mode: 0777

