---
- hosts: all
  tasks:
    - name: Transfer the script
      copy: src=/tmp/Mon115015 dest=/tmp/Mon115015 mode=0777
      register: result_copy

    - name: Execute the script and verification script
      command: sh /tmp/Mon115015 > /tmp/Mon115015.log
      register: result_run
    - debug: var=result_run.stdout_lines
