---
- hosts: abcz
  become: true
  become_user: root
  tasks:
    - name: Transfer the script
      copy: src=/tmp/test dest=/tmp/test mode=0777
      register: result_copy

    - name: Execute the script and verification script
      script: /tmp/test
      register: result_run
   # - debug: var=result_run.stdout_lines
    - name: Fetching the User Details
      fetch:
        src: /tmp/cscdxc1155
        dest: /home/world/ansible/nwr/usercreation/userdetails/details/unme-{{ inventory_hostname }}
        register: output
        ignore_errors: yes
        flat: yes

