---
- hosts: test
  become: true
  become_user: root
  tasks:
  - name: User Removal Task
    user: name=phillipp state=absent remove=yes
    register: userremoval
  - debug: msg="User phillipp has been removed from {{ ansible_hostname }}"
    when: userremoval.changed
  - debug: var=userremoval
