---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: run the script
      script: /home/sverma/ansible/scripts/fscheck_new.sh
      register: output

    - debug: var=output.stdout_lines
